services:
  - type: web
    name: vaulttag
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: POLYGON_RPC_URL
        value: https://rpc-amoy.polygon.technology
      - key: ADMIN_PRIVATE_KEY
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
      - key: PINATA_JWT
        sync: false
      - key: PINATA_GATEWAY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: FRONTEND_URL
        sync: false
